new/src/Entity/Game.php
<?php
declare(strict_types=1);

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use App\Enum\CompletionEstimate as CompletionEstimateEnum;
use App\Enum\Platform as PlatformEnum;
use App\Repository\GameRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GameRepository::class)]
#[ORM\Table(name: "mygamecollection")]
class Game
{
    public function __construct(

        #[ORM\Id]
        #[ORM\Column]
        private int $id,

        #[ORM\Column]
        private string $name,
       
        #[ORM\Column]
        private string $platform,
       
        #[ORM\Column(name: "backcompat")]
        private ?bool $backwardsCompatible,
       
        #[ORM\Column(name: "kinect_required")]
        private ?bool $kinectRequired,
       
        #[ORM\Column(name: "peripheral_required")]
        private ?bool $peripheralRequired,
       
        #[ORM\Column]
        private ?bool $onlineMultiplayer,
       
        #[ORM\Column(name: "completion_perc")]
        private int $completionPercentage,
       
        #[ORM\Column(name: "completion_estimate")]
        private string $completionEstimate,
       
        #[ORM\Column(name: "hours_played")]
        private float $hoursPlayed,
       
        #[ORM\Column(name: "achievements_won")]
        private int $achievementsWon,
       
        #[ORM\Column(name: "achievements_total")]
        private int $achievementsTotal,
       
        #[ORM\Column(name: "gamerscore_won")]
        private int $gamerscoreWon,
       
        #[ORM\Column(name: "gamerscore_total")]
        private int $gamerscoreTotal,
       
        #[ORM\Column(name: "ta_score")]
        private int $taScore,
       
        #[ORM\Column(name: "ta_total")]
        private int $taTotal,
       
        #[ORM\Column(name: "dlc")]
        private bool $hasDlc,
       
        #[ORM\Column(name: "dlc_completion")]
        private int $dlcCompletionPercentage,
       
        #[ORM\Column(name: "site_rating")]
        private float $siteRating,
       
        #[ORM\Column]
        private string $format,
       
        #[ORM\Column]
        private string $status,

        #[ORM\Column(name: "shortlist_order")]
        private int $shortlistOrder,

        #[ORM\Column]
        private int $ranking,
       
        #[ORM\Column(name: "walkthrough_url")]
        private ?string $walkthroughUrl,
       
        #[ORM\Column(name: "game_url")]
        private string $gameUrl,
       
        #[ORM\Column(name: "last_modified", type: "datetime")]
        private DateTime $lastModified,
       
        #[ORM\Column(name: "date_created", type: "datetime")]
        private DateTime $created,
   
        #[ORM\Column(name: "completion_date")]
        private ?DateTime $completionDate = null,
       
        #[ORM\Column(name: "purchased_price")]
        private ?float $purchasedPrice = null,
       
        #[ORM\Column(name: "current_price")]
        private ?float $currentPrice = null,
       
        #[ORM\Column(name: "regular_price")]
        private ?float $regularPrice = null,
    ) {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getPlatform(): string
    {
        return $this->platform;
    }

    public function getPlatformClass(): string
    {
        return match($this->platform) {
            PlatformEnum::PLATFORM_360 => 'x36',
            PlatformEnum::PLATFORM_XB1 => 'xb1',
            PlatformEnum::PLATFORM_XSX => 'xsx',
            PlatformEnum::PLATFORM_WIN => 'win',
            PlatformEnum::PLATFORM_ANDROID,
            PlatformEnum::PLATFORM_WEB => 'mob',
            PlatformEnum::PLATFORM_SWITCH => 'switch',

            default => 'xsx',
        };
    }

    public function getPlatformImg(): string
    {
        return match($this->platform) {
            PlatformEnum::PLATFORM_360 => 'img/xbox-360.png',
            PlatformEnum::PLATFORM_XB1 => 'img/xbox-one.png',
            PlatformEnum::PLATFORM_XSX => 'img/xbox-series-x-s.png',
            PlatformEnum::PLATFORM_WIN => 'img/windows.png',
            PlatformEnum::PLATFORM_ANDROID => 'img/android.png',
            PlatformEnum::PLATFORM_WEB => 'img/web.png',
            PlatformEnum::PLATFORM_SWITCH => 'img/nintendo-switch.png',

            default => 'img/xbox-one.png',
        };
    }

    public function isBackwardsCompatible(): ?bool
    {
        return $this->backwardsCompatible;
    }

    public function getBackwardsCompatibleClass(): string
    {
        return $this->backwardsCompatible == true ? 'green' : 'red';
    }

    public function isKinectRequired(): ?bool
    {
        return $this->kinectRequired;
    }
   
    public function getKinectRequiredClass(): string
    {
        return $this->kinectRequired == true ? 'red' : 'green';
    }

    public function isPeripheralRequired(): ?bool
    {
        return $this->peripheralRequired;
    }

    public function getPeripheralRequiredClass(): string
    {
        return $this->peripheralRequired == true ? 'red' : 'green';
    }

    public function isOnlineMultiplayer(): ?bool
    {
        return $this->onlineMultiplayer;
    }

    public function getOnlineMultiplayerClass(): string
    {
        return $this->onlineMultiplayer == true ? 'red' : 'green';
    }

    public function getBackwardsCompatibleCompleteClass(): string
    {
        return match(true) {
            ($this->kinectRequired || ($this->peripheralRequired && !$this->onlineMultiplayer)) => 'warning',
            (!$this->backwardsCompatible && $this->onlineMultiplayer) => 'danger',
            ($this->backwardsCompatible) => 'success',
            default => '',
        };
    }

    public function getCompletionPercentage(): int
    {
        return $this->completionPercentage;
    }

    public function getCompletionPercentageClass(): string
    {
        return match($this->completionPercentage) {
            0 => '',
            100 => 'success',
            default => 'warning',
        };
    }

    public function getCompletionEstimate(): string
    {
        return $this->completionEstimate;
    }

    public function getCompletionEstimateClass(): string
    {
        return match($this->completionEstimate) {
            CompletionEstimateEnum::COMP_EST_1000H,
            CompletionEstimateEnum::COMP_EST_750H,
            CompletionEstimateEnum::COMP_EST_500H,
            CompletionEstimateEnum::COMP_EST_300H,
            CompletionEstimateEnum::COMP_EST_200H, 
            CompletionEstimateEnum::COMP_EST_150H, 
            CompletionEstimateEnum::COMP_EST_120H, 
            CompletionEstimateEnum::COMP_EST_100H => 'danger',

            CompletionEstimateEnum::COMP_EST_40H,
            CompletionEstimateEnum::COMP_EST_50H,
            CompletionEstimateEnum::COMP_EST_60H,
            CompletionEstimateEnum::COMP_EST_80H => 'warning',

            default => '',
        };
    }

    public function getHoursPlayed(): float
    {
        return $this->hoursPlayed;
    }

    public function getAchievementsWon(): int
    {
        return $this->achievementsWon;
    }

    public function getAchievementsTotal(): int
    {
        return $this->achievementsTotal;
    }

    public function getGamerscoreWon(): int
    {
        return $this->gamerscoreWon;
    }

    public function getGamerscoreTotal(): int
    {
        return $this->gamerscoreTotal;
    }

    public function getTaScore(): int
    {
        return $this->taScore;
    }

    public function getTaTotal(): int
    {
        return $this->taTotal;
    }
   
    public function hasDlc(): bool
    {
        return $this->hasDlc;
    }

    public function getDlcCompletion(): int
    {
        return $this->dlcCompletionPercentage;
    }

    public function getDlcCompletionClass(): string
    {
        return match($this->dlcCompletionPercentage) {
            100 => 'green',
            0 => 'red',
            default => 'orange',
        };
    }

    public function getCompletionDate(): ?DateTime
    {
        return $this->completionDate;
    }

    public function getSiteRating(): float
    {
        return $this->siteRating;
    }
   
    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function getFormatClass(): string
    {
        return match($this->format) {
            'Disc' => 'warning',
            default => '',
        };
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function getPurchasedPrice(): ?float
    {
        return $this->purchasedPrice;
    }
 
    public function getCurrentPrice(): ?float
    {
        return $this->currentPrice;
    }

    public function getRegularPrice(): ?float
    {
        return $this->regularPrice;
    }

    public function getShortlistOrder(): int
    {
        return $this->shortlistOrder;
    }

    public function getRanking(): int
    {
        return $this->ranking;
    }

    public function getWalkthroughUrl(): ?string
    {
        return $this->walkthroughUrl;
    }

    public function getGameUrl(): string
    {
        return $this->gameUrl;
    }

    public function getLastModified(): DateTime
    {
        return $this->lastModified;
    }

    public function getCreated(): DateTime
    {
        return $this->created;
    }

    public function getRatio(): float
    {
        return $this->gamerscoreTotal > 0 ? floatval($this->taTotal / $this->gamerscoreTotal) : 1;
    }

    public function getRatioClass(): string
    {
        $ratio = $this->getRatio();
        return match(true) {
            ($ratio < 2) => 'ratio-veryeasy',
            ($ratio < 3) => 'ratio-easy',
            ($ratio < 4) => 'ratio-medium',
            ($ratio < 5) => 'ratio-hard',
            default => 'ratio-veryhard',
        };
    }

    public function setBackwardsCompatible(?bool $backcompat): self
    {

new/src/Controller/RankingController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Repository\GameRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RankingController extends AbstractController
{
    public function __construct(private readonly GameRepository $gameRepository)
    {
    }

    #[Route("/ranking", name: "ranking")]
    public function ranking(): Response
    {
        $games = $this->gameRepository->fetchTwoRankingGames();
        $stats = $this->gameRepository->fetchRankingStats();

        return $this->render('ranking/index.html.twig', [
            'game1' => $games[0],
            'game2' => $games[1],
            'stats' => $stats,
        ]);
    }

    #[Route("/ranking/choose/{gameId}/{otherGameId}", name: "ranking_choose", requirements: ['gameId' => '\d+', 'otherGameId' => '\d+'])]
    public function choose(
        int $gameId,
        int $otherGameId,
        ManagerRegistry $doctrine
    ): Response {
        $game = $this->gameRepository->find($gameId);
        $otherGame = $this->gameRepository->find($otherGameId);

        if ($game->getRanking() > 0 && $otherGame->getRanking() > 0) {
            //both games have already been ranked, switch rankings and save
            $t = $game->getRanking();
            $game->setRanking($otherGame->getRanking());
            $otherGame->setRanking($t);

        } elseif ($game->getRanking() === 0 && $otherGame->getRanking() > 0) {
            //insert chosen game above other, ranked game
            $this->gameRepository->shiftRankingDownAt($otherGame->getRanking());
            $game->setRanking($otherGame->getRanking());
            $otherGame->setRanking($otherGame->getRanking() + 1);

        } elseif ($game->getRanking() === 0 && $otherGame->getRanking() === 0) {
            //both games have no ranking, insert them below lowest ranked game
            $lowestRanking = $this->gameRepository->getLowestRanking();
            $game->setRanking($lowestRanking + 1);
            $otherGame->setRanking($lowestRanking + 2);
        }

        $manager = $doctrine->getManager();
        $manager->persist($game);
        $manager->persist($otherGame);
        $manager->flush();

        return $this->redirectToRoute('ranking');
    }
}

new/templates/ranking/game.html.twig
<div class="ranking">
    <table class="table table-condensed table-hover">
        <tr class="table-striped table-{{ game.completionPercentageClass }}">
            <td><strong><a href="{{ game.gameUrl }}" target="_blank">{{ game.name }}</a></strong></td>
        </tr>
        <tr>
            <td>Platform: <img src="{{ game.platformImg }}"/> {{ game.platform }}</td>
        </tr>
        <tr>
            <td class="{{ game.completionEstimateClass }}">Completion estimate: {{ game.completionEstimate }}</td>
        </tr>
        <tr>
            <td>Ratio: <div class="ratiocircle {{ game.ratioClass }}">&nbsp;</div> {{ game.ratio|round(2) }}</td>
        </tr>
        <tr>
            <td>Site rating: {{ game.siteRating }}</td>
        </tr>
        <tr>
            <td>Walkthrough: {% if game.walkthroughUrl %}<strong><a href="{{ game.walkthroughUrl }}" target="_blank">yes</a></strong>{% else %}no{% endif %}</td>
        </tr>
        <tr>
            <td>Purchase price: {% if game.purchasedPrice > 0 %}{{ game.purchasedPrice|format_currency('EUR') }}{% else %}FREE{% endif %}</td>
        </tr>
        {% if game.completionPercentage > 0 %}
            <tr>
                <td class="{{ game.completionPercentageClass }}">Completion percentage: {{ game.completionPercentage }}%
                </td>
            </tr>
            <tr>
                <td>Hours played: {{ game.hoursPlayed|number_format(2) }}</td>
            </tr>
            <tr>
                <td>Achievements: {{ game.achievementsWon }}/{{ game.achievementsTotal }}</td>
            </tr>
        {% else %}
            <tr><td>Not started</td></tr>
            <tr><td>&nbsp;</td></tr>
            <tr><td>&nbsp;</td></tr>
        {% endif %}
        <tr>
            <td><a class="btn btn-danger" href="/ranking/choose/{{ game.id }}/{{ otherGame.id }}">CHOOSE</a></td>
        </tr>
    </table>
</div>

new/templates/ranking/index.html.twig
{% extends 'index.html.twig' %}

{% block body %}
    <div class="container">
        <h1>
            <a href="https://www.trueachievements.com/" target="_blank" class="link-secondary link-underline-opacity-0 link-underline-opacity-100-hover">My Game Collection</a> - Rank your games
            <a href="/"><span class="bi-arrow-left-circle-fill"></span></a>
        </h1>
        <h3>Which would you rather play? (<a href="">skip)</a></h3>
        {% include 'ranking/game.html.twig' with { 'game': game1, 'otherGame': game2 } %}
        {% include 'ranking/game.html.twig' with { 'game': game2, 'otherGame': game1 } %}
        <div class="text-muted" id="ranking-stats">
            <ul>
                <li>Unranked games: {{ stats.unrankedCount }}</li>
                <li>
                    Top 5 games:<ol>
                        {% for game in stats.top5 %}
                            <li>{{ game.name }}</li>
                        {% endfor %}
                    </ol>
                </li>
                <li>
                    Bottom 5 games:<ol>
                        {% for game in stats.bottom5 %}
                            <li>{{ game.name }}</li>
                        {% endfor %}
                    </ol>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}